import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b border-[var(--color-border)] bg-white">
          <div className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
            <Link href="/" className="text-[var(--color-navy)] font-bold text-lg">
              RA Portal
            </Link>
            <nav className="flex gap-4">
              <Link href="/management" className="text-sm hover:underline">Management View</Link>
              <Link href="/merchant" className="text-sm hover:underline">Merchant wise Final</Link>
              <Link href="/billed" className="text-sm hover:underline">Billed Detailed</Link>
              <Link href="/unbilled" className="text-sm hover:underline">Unbilled Detailed</Link>
            </nav>
          </div>
        </header>
        <main className="mx-auto max-w-6xl px-4 py-6">{children}</main>
      </body>
    </html>
  );
}
